# Generated by Django 2.0.4 on 2018-04-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article1',
        ),
    ]
