# Generated by Django 2.0.4 on 2018-05-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180430_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='article1',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
